project:
  type: website
  output-dir: docs

website:
  title: "temp_website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - project.qmd
      - Travel.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    toc: true
    toc-depth: 3
    toc-location: left



